#!/bin/bash
#
# Install Qt Color Scheme file

mkdir -p "$HOME/.config/qt5ct/colors/"
curl \
  -fsSL https://github.com/moktavizen/breeze-libadwaita/raw/main/qtct/color-schemes/breeze_libadwaita_dark.conf \
  -o "$HOME/.config/qt5ct/colors/breeze_libadwaita_dark.conf"

mkdir -p "$HOME/.config/qt6ct/colors/"
curl \
  -fsSL https://github.com/moktavizen/breeze-libadwaita/raw/main/qtct/color-schemes/breeze_libadwaita_dark.conf \
  -o "$HOME/.config/qt6ct/colors/breeze_libadwaita_dark.conf"
